version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SESSION_SECRET=d4f8e7c2a9b6f3e1c0d7a5e9f2b4c6a8d1e3f7b9c0a2d4e6f8b1c3a7d9e5f2
      - MONGODB_URI=mongodb+srv://venternevertony:Rustam1985@ex01.8zvjqdt.mongodb.net/mydatabase?retryWrites=true&w=majority
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjkzNzY4MDAwLCJleHAiOjE2OTM3NzE2MDB9.4f5c8b1a2d3e4f5g6h7i8j9k0lmnopqrstuvwx
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: